# Generated by Django 4.1.7 on 2023-03-19 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0003_rename_cashier_group_id_groupincome_cashier_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupincome",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="groupincome",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="groupincome",
            name="updated_date",
        ),
    ]
