# Generated by Django 4.1.7 on 2023-03-19 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_rename_active_expense_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="expensewarning",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="groupexpense",
            old_name="cashier_group_id",
            new_name="cashier_group",
        ),
        migrations.RenameField(
            model_name="groupexpense",
            old_name="expense_id",
            new_name="expense",
        ),
    ]
