# Generated by Django 4.1.7 on 2023-04-16 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expense", "0005_remove_expensewarning_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensewarning",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_warnings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expensewarning",
            name="warn_level",
            field=models.CharField(
                choices=[
                    ("WARN_SIMPLE", "WARN_SIMPLE"),
                    ("WARN_MEDIUM", "WARN_MEDIUM"),
                ],
                max_length=255,
            ),
        ),
    ]
