# Generated by Django 4.1.7 on 2023-03-15 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_cashiergroup_supervisor_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashiergroup",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
