# Generated by Django 4.1.7 on 2023-03-19 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_rename_active_cashiergroup_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashiergroup",
            old_name="supervisor_id",
            new_name="supervisor",
        ),
    ]
